export const NOUNS = [
  {
    kanji: "鳥",
    hirigana: "とり",
    english: "bird",
    level: "easy",
    animate: true,
  },
  {
    kanji: "男",
    hirigana: "おとこのひと",
    english: "person",
    level: "easy",
    animate: true,
  },
  {
    kanji: "コート",
    hirigana: "コート",
    english: "coat",
    level: "easy",
    animate: false,
  },
  {
    kanji: "機械",
    hirigana: "きかい",
    english: "machine",
    level: "hard",
    animate: false,
  },
  {
    kanji: "お客",
    hirigana: "おきゃく",
    english: "customer",
    level: "hard",
    animate: false,
  },
  {
    kanji: "娘",
    hirigana: "むすめ",
    english: "daughter",
    level: "hard",
    animate: false,
  },
  {
    kanji: "お金",
    hirigana: "おかね",
    english: "money",
    level: "hard",
    animate: false,
  },
  {
    kanji: "日記",
    hirigana: "にっき",
    english: "diary",
    level: "hard",
    animate: false,
  },
  {
    kanji: "小麦粉",
    hirigana: "こむぎこ",
    english: "flour",
    level: "hard",
    animate: false,
  },
  {
    kanji: "夫",
    hirigana: "おっと",
    english: "husband",
    level: "hard",
    animate: false,
  },
];
